### ISSUE TITLE
`npx browserslist --update-db` -> command failed

### ISSUE THREAD

**Issue by Millerlm012** [nodejs/snap#12]
I'm having some difficulties with the `npx browserslist --update-db` command. I went ahead and installed Node via `sudo snap install node --classic --channel=14`, and everything seems to install fine.

`node -v` -> v14.7.1
`npm -v` -> 6.14.3
`npx -v` -> 6.14.13

After issuing the `npx browserslist --update-db` command, I'm receiving en error "Command failed: npm show caniuse-lite --json", but if I execute `npm show caniuse-lite --json` manually the command works fine. This is running on Ubuntu 20.04. When I've installed Node on both Windows and Mac, `npx browserslist --update-db` works great which leads me to believe I'm missing a step or something doesn't get properly set up with the snap install. Any help would be greatly appreciated!

**Comment by rvagg** [comment]
So, this is a bit beyond my top-of-mind expertise to answer directly and would need some investigative time to figure out what's actually going on, but it's roughly similar to a bunch of other problems with invoking snaps due to the way they redirect the main executable through the `snap` executable to invoke the right version. Basically when you run `node` it goes to `/snap/bin/node` which is just a link to `/usr/bin/snap` which then looks up how to invoke "node" and you get the right version and you get proper isolation and safe atomic upgrades of your snaps and all of that niceness. But it kind of sucks for very specific situations where the executable has trouble figuring out how it's invoked.

For your case, you're going through `child_process.execFile()` to do the `npm show caniuse-lite --json`, but there's something about `execFile()` and maybe all of the fork/span utilities, that doesn't like this indirect execution of `node` -> `snap` -> `node`. I'm not sure if it's to do with what `snap` is doing prior to executing `node` or the fact that your original `node` isn't actually the `node` that finally gets executed. :shrug:.

The simplest workaround, other than not using the snap for this, is to execute the snap's `node` executable directly. `/snap/node/current/bin/node` is where it sits, or at least it's a symlink to the current `node` that's installed. There may be problems with long-running processes executing this way and you (probably) miss out on some of the other isolation benefits of snaps (although `node` has "classic" confinement so not much isolation is going on anyway). So if you execute a node program that's having this problem with `/snap/node/current/bin/node` then it _should_ work properly. I think the same may be true for `/snap/node/current/bin/npx`, although since it's executed with a `!#/usr/bin/env` it probably just takes you back to `node` so you could do `/snap/node/current/bin/node /snap/node/current/bin/npx ...` to get the proper effect. 🤞 .

Crappy answer, but there's a bunch of things that the `node` snap has trouble doing, when you reach for too much novelty things break down a bit and we don't yet have solutions (or perhaps those solutions just aren't possible with snaps the way they are now). Snaps are convenient, but when you end up using `node` similar to how you use `bash` maybe it's not surprising that it's not quite a right fit.

**Comment by Millerlm012** [comment]
Thanks @rvagg! There's a lot of insight in your reply that I'll have to dig into here soon. I've been pretty busy, but I'll try some other things and if I find something that works I'll respond back here! Again, thank you so much!
