### ISSUE TITLE
Node.js 22.1.0 installed instead of 22.4.0

### ISSUE THREAD

**Issue by MikeMcC399** [nodejs/snap#67]
## Issue

```text
sudo snap install node --classic --channel=22
node (22/stable) 22.1.0 from OpenJS Foundation (iojs✓) installed
```

installs outdated Node.js `22.1.0`

Branch [node22](https://github.com/nodejs/snap/tree/node22) is however showing in https://github.com/nodejs/snap/commit/5ed12ec4223f295b05e581127215f640d6ffaed4 that it was updated to `22.4.0`.

## Environment

Ubuntu `22.04.4` LTS

## Desired

Node.js `22.4.0` (or later) should be installed when running

```shell
sudo snap install node --classic --channel=22
```

See https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V22.md for current latest Node.js `22.x`

**Comment by rvagg** [comment]
<img width="682" alt="Screenshot 2024-07-08 at 10 14 26 AM" src="https://github.com/nodejs/snap/assets/495647/d693c930-1e47-422c-9471-7cdd084a19d7">

Odd. The [snap store](https://snapcraft.io/node) has the last as 22.1, but the code everywhere has 22.4. Including the builds @ https://launchpad.net/~openjs/+snap/node22

Snap config in launchpad has this though:

<img width="640" alt="Screenshot 2024-07-08 at 10 15 54 AM" src="https://github.com/nodejs/snap/assets/495647/f5186232-69de-47e8-a125-32774e4d1214">

It should have a track listed! I have no idea how that's fallen out since it _was_ working. I'll set it to `22` and re-trigger the latest ones and we'll have to wait and see if it works.

**Comment by rvagg** [comment]
<img width="754" alt="Screenshot 2024-07-08 at 12 42 51 PM" src="https://github.com/nodejs/snap/assets/495647/13a29a45-6e44-44ae-b5b0-277718724c8f">

should be good now, thanks for reporting

**Comment by MikeMcC399** [comment]
@rvagg 

Thanks! I can confirm it's now installing `22.4.0` as expected.
